services:
  - type: web
    name: ai-lie-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
